dry_run: false   # set true to preview/log only (no orders)

risk:
  account_equity: 50000        # used only if use_broker_equity: false
  use_broker_equity: true      # pull live equity from Alpaca paper acct
  risk_per_trade_pct: 0.02     # 2% risk per trade
  atr_multiple_stop: 1.5       # stop = 1.5 * ATR(14)
  reward_multiple: 2.0         # target = entry + 2R
  max_total_risk_pct: 0.10     # cap total risk across open stops
  bp_utilization: 0.95         # spend at most 95% of available buying power
  min_shares: 1

signals:
  sr_pivots:
    lookback: 60
    left: 3
    right: 3
    near_pct: 0.025            # was 0.015 — loosen proximity
    near_atr_mult: 0.75        # was 0.5  — allow wider ATR tolerance
    ema50_fallback_pct: 0.025  # re-enable EMA50 fallback
    yesterday_touch_ok: true   # NEW: accept prior-bar proximity as valid

# --- momentum quality controls ---
momentum:
  rsi_filter: true
  rsi_threshold: 50
  use_macd_expansion: false    # was true — expansion becomes optional/bonus
  expansion_lookback: 3
  expansion_min_steps: 1
  zero_line_mode: "confirm"    # was "cross" — confirm MACD sign only
  zero_cross_lookback: 3

# --- volume confirmation (any-of) ---
volume:
  rvol_window: 20
  rvol_threshold: 1.15         # was 1.20/1.30 — slightly easier participation
  ad_trend_lookback: 3
  obv_confirm: true            # counts as one check if true
  min_checks_true: 1           # NEW: require at least N of {RVOL, A/D, OBV}

regime:
  enabled: true
  adx_min: 16                  # was 18 — a bit more permissive
  atr_pct_min: 0.010           # was 0.015 — allow lower-vol environments
  use_chop: true
  chop_window: 14
  chop_max: 60                 # was 55 — allow a touch more range

logging:
  explain_rejects: true

fundamentals:
  enabled: false
  min_price: 5
  max_price: 1000
  min_avg_vol: 1000000
  earnings_blackout_days: 3
  sectors_allow: []
  sectors_deny: []
  profitability:
    enabled: false
    require_positive_eps_ttm: true
    min_revenue_yoy_growth_pct: 0
  news:
    enabled: true
    lookback_days: 3
    min_sentiment: -0.10
    forbid_red_flags:
      - bankruptcy
      - fraud
      - "going concern"

trading:
  # NOTE: MTF can count as a 6th "bonus" energy; keep min_score at 4 so you're not forced to pass volume+MTF simultaneously.
  min_score: 4
  confirm_before_place: true
  time_in_force: "gtc"
  order_type: "market"
  max_signals_per_run: 0

  # ---- Higher timeframe (MTF) confirmation ----
  mtf:
    enabled: true
    timeframe: "W"
    trend_filter: "macd"       # MACD-based weekly momentum tends to work better
    ema_fast: 20
    ema_slow: 50
    macd_fast: 12
    macd_slow: 26
    macd_signal: 9
    require_alignment: true
    reject_on_mismatch: false  # don't veto — it's a bonus energy instead
    counts_as_energy: true     # NEW: add +1 to score when aligned

### ---------- For backtesting ---------- ###
backtest:
  start_days_ago: 600
  initial_equity: 50000
  commission_per_share: 0.00
  slippage_bps: 2.0
  allow_short: true
  max_open_positions: 6
  max_total_risk_pct: 0.08
  max_new_trades_per_week: 3
  touch_priority: "stop_first"
  bp_multiple: 1.0               # cap notional per trade to 1.0× equity (set 2.0 for margin)
  halt_on_equity_at_or_below: 0  # block new trades if equity <= this
  force_close_on_end: true       # liquidate all open positions on final day

  # Breakeven controls (engine.py uses these)
  breakeven_at_R: 1.0
  breakeven_intrabar: "favor_be"   # or "favor_stop"

  # Backtest entry model (independent of live order_type)
  entry_model:
    type: "limit_retrace"          # "market" or "limit_retrace"
    retrace_to: "EMA20"
    atr_fraction: 0.25
    horizon_days: 3
