dry_run: false   # set true to preview/log only (no orders)

risk:
  account_equity: 50000        # used only if use_broker_equity: false
  use_broker_equity: true      # pull live equity from Alpaca paper acct
  risk_per_trade_pct: 0.02     # 2% risk per trade
  atr_multiple_stop: 1.5       # stop = 1.5 * ATR(14)
  reward_multiple: 2.0         # target = entry + 2R
  max_total_risk_pct: 0.10     # cap total risk across open stops
  bp_utilization: 0.95         # spend at most 95% of available buying power
  min_shares: 1

signals:
  sr_pivots:
    lookback: 60
    left: 3
    right: 3
    near_pct: 0.02
    near_atr_mult: 0.50
    ema50_fallback_pct: 0.025    # fallback tolerance (percent of price); set null to disable check
    allow_fallback_as_core: false # if true, EMA50 proximity alone can satisfy S/R energy
    # yesterday_touch_ok: true    # enabled by default in code

# --- cycle (stochastic) hysteresis ---
cycle:
  rise_bars: 0            # require %K strictly rising (or falling) N bars before trigger (0=off)
  require_d_slope: false  # demand SlowD rising for long trigger / falling for short

# --- momentum quality controls ---
momentum:
  rsi_filter: true
  rsi_threshold: 50
  use_macd_expansion: false      # if you re-enable, keep expansion_min_steps: 1
  expansion_lookback: 3
  expansion_min_steps: 1
  zero_line_mode: "confirm"
  zero_cross_lookback: 3

# --- volume confirmation (any-of) ---
volume:
  rvol_window: 20
  rvol_threshold: 1.20
  ad_trend_lookback: 3
  obv_mode: "tick"               # or "slope"
  min_components: 2              # require 2 of {RVOL, AD, OBV}

# --- fractal/volatility (5th core energy) ---
fractal:
  adx_min: 18            # ADX threshold for trend strength (passes if missing)
  use_chop: true         # include choppiness constraint
  chop_window: 14
  chop_max: 58

regime:
  enabled: true
  adx_min: 16
  atr_pct_min: 0.010
  use_chop: true
  chop_window: 14
  chop_max: 60

logging:
  explain_rejects: true

fundamentals:
  enabled: false
  min_price: 5
  max_price: 1000
  min_avg_vol: 1000000
  earnings_blackout_days: 3
  sectors_allow: []
  sectors_deny: []
  profitability:
    enabled: false
    require_positive_eps_ttm: true
    min_revenue_yoy_growth_pct: 0
  news:
    enabled: true
    lookback_days: 3
    min_sentiment: -0.10
    forbid_red_flags:
      - bankruptcy
      - fraud
      - "going concern"

trading:
  # MTF counts as a 6th "bonus" energy but also vetoes mismatches
  min_score: 4             # effective score threshold (core + MTF bonus)
  min_core_energies: 4     # STRICT: must have at least this many of 5 core before bonus
  confirm_before_place: true
  time_in_force: "gtc"
  order_type: "market"           # live only; backtest has its own entry model
  max_signals_per_run: 0

  # Optional weighting of core energies (trend, momentum, cycle, sr, fractal)
  energy_weights:
    trend: 1.0
    momentum: 1.0
    cycle: 1.0
    sr: 1.0
    fractal: 1.0

  # Post-energy pattern trigger (must pass if enabled)
  patterns:
    enabled: false
    modes: ["engulf", "inside_break", "nr4_break"]

  # ---- Higher timeframe (MTF) confirmation ----
  mtf:
    enabled: true
    timeframe: "W"
    trend_filter: "ema"          # or "macd"
    ema_fast: 20
    ema_slow: 50
    macd_fast: 12
    macd_slow: 26
    macd_signal: 9
    counts_as_energy: true       # bonus point if aligned
    reject_on_mismatch: true     # veto trades against weekly

### ---------- For backtesting ---------- ###
backtest:
  start_days_ago: 600
  initial_equity: 50000
  commission_per_share: 0.00
  slippage_bps: 2.0
  allow_short: false             # optional: start long-only; re-enable later
  max_open_positions: 6
  max_total_risk_pct: 0.08
  max_new_trades_per_week: 3
  touch_priority: "stop_first"
  bp_multiple: 1.0
  halt_on_equity_at_or_below: 0
  force_close_on_end: true

  # Breakeven controls (engine.py uses these)
  breakeven_at_R: 0.8
  breakeven_intrabar: "favor_be"   # or "favor_stop"

  # Backtest entry model (independent of live order_type)
  entry_model:
    type: "market"        # "limit_retrace" or "market"
    retrace_to: "EMA20"
    atr_fraction: 0.20
    horizon_days: 3
