dry_run: false   # set true to preview/log only (no orders)

risk:
  account_equity: 50000        # used only if use_broker_equity: false
  use_broker_equity: true      # pull live equity from Alpaca paper acct
  risk_per_trade_pct: 0.01     # lowered to 1% risk per trade (stricter)
  atr_multiple_stop: 1.4       # stabilizer: tighten stop multiple from 1.8
  reward_multiple: 2.2         # single target evaluation
  max_total_risk_pct: 0.10     # cap total risk across open stops
  bp_utilization: 0.95         # spend at most 95% of available buying power
  min_shares: 1
  min_stop_pct: 0.0            # disable absolute stop floor; use pivots+ATR padding
  max_position_notional_pct: 0.25   # cap single position notional to 25% of equity
  pad_atr_for_pivot_stop: 0.20 # slightly reduced ATR padding beyond pivot for Burns pivot stop

signals:
  sr_pivots:
    lookback: 60
    left: 3
    right: 3
    near_pct: 0.02
    near_atr_mult: 0.50
    ema50_fallback_pct: 0.025    # fallback tolerance (percent of price); set null to disable check
    allow_fallback_as_core: false # if true, EMA50 proximity alone can satisfy S/R energy
    tolerance_mode: "min"        # choose narrower of ATR*mult vs pct (stricter); "max" uses wider
    # yesterday_touch_ok: true    # enabled by default in code
    # Phase 3 (optional) pivot cluster gating (currently disabled for baseline)
    cluster:
      enabled: true          # require pivot cluster confirmation
      min_pivots: 2          # minimum distinct pivot lows (or highs) comprising cluster
      lookback: 90           # bars to search for cluster pivots
      max_span_pct: 0.02     # vertical span (high-low of cluster) / anchor price
      max_price_dist_pct: 0.035  # price must be within this % of anchor pivot level
    fib:
      enabled: true          # optional Fibonacci confluence check

# --- cycle (stochastic) hysteresis ---
cycle:
  stoch_mode: "burns_5_3_2"  # use Burns timing (5-3-2) instead of legacy 14-3-3
  from_extreme: true          # require cross to originate from oversold/overbought
  lookback: 10                # bars window to find the most recent valid cross
  extreme_lookback: 10        # prior window for origin-from-extreme check
  oversold: 25                # 25/75 often suits daily swings better than 20/80
  overbought: 75
  confirm_bars: 1             # require %K to continue rising/falling at least N bars
  relax_midline_in_value_zone: 5.0  # loosen midline by N points when price is in value zone
  rise_bars: 2            # broaden cycle confirmation window
  require_d_slope: false  # demand SlowD rising for long trigger / falling for short

# --- momentum quality controls ---
momentum:
  recent_confirm_lookback: 2      # allow MACD cross within last N bars (alignment window)
  rsi_filter: true
  rsi_threshold: 55
  use_macd_expansion: false      # if you re-enable, keep expansion_min_steps: 1
  expansion_lookback: 3
  expansion_min_steps: 1
  zero_line_mode: "confirm"
  zero_cross_lookback: 3
  macd_abs_min: 0.06             # keep momentum floor
  # minimum MACD-vs-signal distance to avoid hairline crosses (in MACD units)
  min_cross_distance: 0.03

# --- volume confirmation (any-of) ---
volume:
  rvol_window: 20
  rvol_threshold: 1.20
  ad_trend_lookback: 3
  obv_mode: "tick"               # or "slope"
  min_components: 2              # require 2 of {RVOL, AD, OBV}
  window: 20                     # window for AD/OBV slope components and for RVOL aggregation

# (Removed) fractal energy. Pure Burns uses Scale (weekly momentum) as the 5th energy.

regime:
  enabled: true
  adx_min: 18            # raised from 16 to avoid weak regime entries
  atr_pct_min: 0.010
  use_chop: true
  chop_window: 14
  chop_max: 60

logging:
  explain_rejects: true

fundamentals:
  enabled: false
  earnings_blackout: true          # unified toggle for earnings blackout screening (prefetch + fill veto)
  exit_before_earnings: true       # optional: exit positions before upcoming earnings event
  prescreen_price: true      # when false, skip price fetch in fundamentals prescreen (falls back to fail-open keep)
  min_price: 5
  max_price: 1000
  earnings_blackout_days: 3
  sectors_allow: []
  sectors_deny: []
  profitability:
    enabled: false
    require_positive_eps_ttm: true
    min_revenue_yoy_growth_pct: 0
  news:
    enabled: false   # default off in backtests to avoid rate limits
    lookback_days: 3
    min_sentiment: -0.10
    forbid_red_flags:
      - bankruptcy
      - fraud
      - "going concern"
  # Backtest-only networking policy and cache settings
  backtest_mode:
    network: prefetch_only   # off | prefetch_only | live_ok
    cache_dir: cache/fundamentals
    ttl_days: 14
    fail_policy: fail_open   # if network=off and cache miss: fail_open | fail_closed

# --- strengthened Trend energy controls (Burns-consistent) ---
trend_energy:
  min_adx: 20                # 18–20 is reasonable; 25 can be too strict
  min_ema_gap_pct: 0.003     # 0.30% min separation between EMA20 and EMA50
  slope:
    lookback: 20
    min_bps_per_day: 1.5     # 1.5 bps/day ≈ 0.015%/day slope on SMA50
    method: "llr"            # linear regression over SMA50
  pivots:
    enabled: true
    lookback: 60
    require_hh_hl: true
signals:
  trend:
    min_points: 3            # 3 of 5
    require_ema20_gt_ema50: true
    slope_lookback: 3
    min_slope_ema50_bp: 0.0
    allow_ema20_slope_substitute: true
    sep_min_atr_mult: 0.25
    require_close_above_ema50: true
    adx_soft_min: 16
    adx_required_if_sep_below_mult: 0.50
    confirm_n_of_m: [2, 3]
  structure_donchian: 20

trading:
  # Pure Burns: require 4-of-5 core energies; no MTF bonus
  min_score: 4
  min_core_energies: 4
  momentum_cycle_or: true
  burns_mode: true
  confirm_before_place: true
  time_in_force: "gtc"
  order_type: "market"
  max_signals_per_run: 0
  # engine acceptance reads this directly (not from filters)
  min_atr_pct: 0.011

  # Revalidate core energies at fill time for limit orders
  core_at_fill:
    enabled: true              # require N-of-5 core at fill (prevents stale fills)
    min_core_energies: 4       # minimum core passes at fill
    require_same_direction: true  # direction must still align at fill

  energy_weights:               # optional weighting (informational)
    trend: 1.0
    momentum: 1.0
    cycle: 1.0
    sr: 1.0
    scale: 1.0

  patterns:                     # post-energy pattern triggers
    enabled: false              # disabled temporarily to expand flow for diagnostics
    modes:
      - engulf
      - inside_break
      - nr4_break

  filters:                      # additional trade-level gating
    min_atr_pct: 0.011          # relaxed to admit slightly lower volatility names
    max_extension_pct: 0.055    # modest tighten
    min_avg_vol50: 0       # liquidity floor (50d avg volume)
    pullback_tolerance_pct: 0.030  # slightly tighter pullback proximity
    value_zone_max_ext_pct: 0.025   # Burns: acceptable extension from EMA20 for valid pullback entry
    value_zone_reject_tail_min: 0.50 # tighten rejection tail requirement (long)
    value_zone_reject_tail_min_short: 0.50 # tighten rejection tail requirement (short)
    value_zone_touch_atr_max: 0.45    # avoid deep fading pulls
    pullback_adx_min: 20             # new: floor for pullback setups only
    cycle_oversold: 25               # SlowK threshold oversold (long)
    cycle_overbought: 75             # SlowK threshold overbought (short)
    cycle_cross_lookback: 3          # bars within which a valid stochastic cross must have occurred
    momentum_hist_expand_lookback: 2 # MACD histogram expansion bars required
    momentum_macd_min: 0.00          # floor for MACD magnitude (Burns often flexible)
  # removed legacy fractal thresholds (Scale covers MTF alignment)

  targets:                      # scaling / runner configuration
    enabled: false              # phase1 disable scaling; evaluate raw expectancy
    primary_R: 2.0              # placeholder (unused while disabled)
    runner_R: 4.0
    scale_out_pct: 0.5
    adx_min_for_runner: 20

  volume_tiebreak_core4: true  # relaxed: allow core-min without volume confirm (diagnostic)

  # Reject extended, weak breakouts (combined gate)
  breakout_extension_gate:
    enabled: true
    hard_ema20_dist_pct: 0.065       # reject above 6.5%
    soft_ema20_dist_pct: 0.045       # soft band above 4.5%
    weak_adx14: 20                   # if ADX < 20 tighten
    weak_ext_pct: 0.040              # max extension when ADX weak
    min_atr_pct: 0.022               # require sufficient ATR% for gating context
    require_volume_in_soft_band: true
    require_cluster_in_soft_band: true
    risk_scale_soft_band: 0.6        # scale risk in soft band
    fill_day_recheck: true

  mtf:                          # higher timeframe confirmation
    enabled: true
    timeframe: "W"
    trend_filter: "macd"
    ema_fast: 20
    ema_slow: 50
    macd_fast: 12
    macd_slow: 26
    macd_signal: 9
    counts_as_energy: false
    filter_at_fill: true
    reject_on_mismatch: false
    slope:                     # weekly slope confirmation/gating
      enabled: true
      indicator: "ema20"       # ema20 | macd_line
      lookback_weeks: 3
      mode: "confirm"          # confirm | gate
      min_norm_slope_per_week: 0.0045  # modest threshold inside suggested band
      deadband: 0.0002
      macd_deadband: 0.05
      ema_gap_min_pct: 0.004
      use_partial_week: false
      log_fields: true

  # Protect against trivial same-day stop-outs on market/limit fills
  same_day_exit_protect:
    enabled: true
    min_adverse_R: 0.40   # require >= 0.4R adverse move on fill day to honor stop_same_day

### ---------- For backtesting ---------- ###
backtest:
  start_days_ago: 600
  # Optional explicit date range (overrides start_days_ago when both provided)
  # Accepts ISO 'YYYY-MM-DD' or 'M/D/YYYY'. If only one given behaves as:
  #   start_date only -> end_date = today
  #   end_date only   -> start_date = end_date - start_days_ago
  start_date: 2024-01-01
  end_date: 2024-12-31
  initial_equity: 50000
  commission_per_share: 0.00
  slippage_bps: 2.0
  allow_short: false             # optional: start long-only; re-enable later
  max_open_positions: 10000       # effectively unlimited for this universe
  max_total_risk_pct: 0.08
  max_new_trades_per_week: 0     # 0 = unlimited
  touch_priority: "stop_first"
  bp_multiple: 1.0
  halt_on_equity_at_or_below: 0
  force_close_on_end: true
  logging:
    write_evaluations_csv: true      # set false to skip evaluations CSV
    write_daily_metrics_csv: true    # set false to skip daily metrics CSV
    write_drawdowns_csv: true        # set false to skip drawdowns CSV
    write_meta: true                 # set false to skip config + meta YAML snapshots
    print_rollups: true              # grouped rollups in console
    print_pending_stats: true        # pending/fill stats + rates in console
    print_reconciliation: true       # reconciliation and audit prints
    print_top_bottom_trades: true    # top/bottom R tables
    print_recap: false               # extra recap from script (engine already prints)
  time_stop:
    enabled: true              # exit if no progress within horizon
    bars: 15                   # bars elapsed
    min_R: 0.5                 # required MFE in R; else exit
  early_stop:                # new soft-stop pruning
    enabled: false
    bars: 0
    min_mfe_R: 0.0
    adverse_atr_mult: 0.0
  gap_fail_safe:             # mitigate large overnight gaps
    enabled: true
    gap_R_multiple: 1.3      # tighter: trigger protective exit sooner
  loss_guard:                # early MAE hard cap
    enabled: true
    mae_R_threshold: 1.2
    bars: 5

  # Burns-aligned evidence-based exit controls
  evidence_exit:
    enabled: true
    pre1R_max_bars: 8        # if not reaching min MFE by this many bars, exit
    pre1R_min_mfe: 0.5       # required MFE in R before 1R; else exit
    momentum_fail: true      # MACD vs signal/zero fail
    cycle_fail: true         # SlowK vs SlowD fail
    value_zone_fail: true    # price lost EMA50 bias
    # --- softening toggles ---
    min_hold_bars: 2
    consecutive_fails_default: 1
    momentum_consecutive: 2
    cycle_consecutive: 3
    value_zone_consecutive: 2

    weights:
      momentum: 0.6
      cycle: 0.6
      value_zone: 1.0
    threshold_single: 1.2
    threshold_two_bar: 1.8

    value_zone_fail_buffer_pct: 0.0015
    cycle_fail_gap_min: 1.5
    momentum_need_zero_cross: false

    setup_overrides:
      pullback:
        cycle_consecutive: 2
      breakout:
        momentum_consecutive: 2

    intraday_recovery:
      enabled: false
      minutes: 60
      require_reclaim: "EMA20"

  # Trail stop to EMA20 after reaching a minimum R
  trail_after_R:
    enabled: true
    start_R: 1.0

  # Exit positions if no fresh bars for a while (data staleness)
  stale_data_exit:
    enabled: true
    max_gap_days: 5

  # Breakeven controls (engine.py uses these)
  breakeven_at_R: 1.0          # re-enabled at 1R for protection
  breakeven_intrabar: "favor_be"   # or "favor_stop"

  # Backtest entry model (independent of live order_type)
  entry_model:
    type: "market"        # switch to market order model
    retrace_to: "EMA20"
    atr_fraction: 0.15
    horizon_days: 3

# Watchlist generation configuration
watchlist:
  universes: ["all"]  # options: sp500, sp1000, sp1500, russell3000, all
  # When 'all' is present, script expands to every supported index.
  # NOTE: 'russell3000' symbols are ALWAYS sourced from IWV ETF holdings (snapshot) – we do not scrape.
  #       This introduces survivorship bias vs historical Russell membership. For historical studies,
  #       consider sourcing point-in-time index data externally.
  alpaca_filter: true     # apply broker active/tradable filter if credentials available
  include_iwv: false       # if true AND russell3000 not in universes, also merge IWV holdings (broad market proxy)
  iwv_ttl_days: 2
  iwv_force_refresh: false
