dry_run: false   # set true to preview/log only (no orders)

risk:
  account_equity: 50000        # used only if use_broker_equity: false
  use_broker_equity: true      # pull live equity from Alpaca paper acct
  risk_per_trade_pct: 0.01     # lowered to 1% risk per trade (stricter)
  atr_multiple_stop: 1.4       # stabilizer: tighten stop multiple from 1.8
  reward_multiple: 2.2         # single target evaluation
  max_total_risk_pct: 0.10     # cap total risk across open stops
  bp_utilization: 0.95         # spend at most 95% of available buying power
  min_shares: 1
  min_stop_pct: 0.010          # minimum stop distance (1% of entry)
  max_position_notional_pct: 0.25   # cap single position notional to 25% of equity
  pad_atr_for_pivot_stop: 0.25 # extra ATR padding beyond pivot for Burns pivot stop

signals:
  sr_pivots:
    lookback: 60
    left: 3
    right: 3
    near_pct: 0.02
    near_atr_mult: 0.50
    ema50_fallback_pct: 0.025    # fallback tolerance (percent of price); set null to disable check
    allow_fallback_as_core: false # if true, EMA50 proximity alone can satisfy S/R energy
    tolerance_mode: "min"        # choose narrower of ATR*mult vs pct (stricter); "max" uses wider
    # yesterday_touch_ok: true    # enabled by default in code
    # Phase 3 (optional) pivot cluster gating (currently disabled for baseline)
    cluster:
      enabled: true          # require pivot cluster confirmation
      min_pivots: 2          # minimum distinct pivot lows (or highs) comprising cluster
      lookback: 90           # bars to search for cluster pivots
      max_span_pct: 0.02     # vertical span (high-low of cluster) / anchor price
      max_price_dist_pct: 0.035  # price must be within this % of anchor pivot level
    fib:
      enabled: true          # optional Fibonacci confluence check

# --- cycle (stochastic) hysteresis ---
cycle:
  rise_bars: 2            # broaden cycle confirmation window
  require_d_slope: false  # demand SlowD rising for long trigger / falling for short

# --- momentum quality controls ---
momentum:
  rsi_filter: true
  rsi_threshold: 55
  use_macd_expansion: false      # if you re-enable, keep expansion_min_steps: 1
  expansion_lookback: 3
  expansion_min_steps: 1
  zero_line_mode: "confirm"
  zero_cross_lookback: 3
  macd_abs_min: 0.06             # keep momentum floor

# --- volume confirmation (any-of) ---
volume:
  rvol_window: 20
  rvol_threshold: 1.20
  ad_trend_lookback: 3
  obv_mode: "tick"               # or "slope"
  min_components: 2              # require 2 of {RVOL, AD, OBV}

# (Removed) fractal energy. Pure Burns uses Scale (weekly momentum) as the 5th energy.

regime:
  enabled: true
  adx_min: 16
  atr_pct_min: 0.010
  use_chop: true
  chop_window: 14
  chop_max: 60

logging:
  explain_rejects: true

fundamentals:
  enabled: false
  min_price: 5
  max_price: 1000
  min_avg_vol: 1000000
  earnings_blackout_days: 3
  sectors_allow: []
  sectors_deny: []
  profitability:
    enabled: false
    require_positive_eps_ttm: true
    min_revenue_yoy_growth_pct: 0
  news:
    enabled: true
    lookback_days: 3
    min_sentiment: -0.10
    forbid_red_flags:
      - bankruptcy
      - fraud
      - "going concern"

trading:
  # Pure Burns: require 4-of-5 core energies; no MTF bonus
  min_score: 4
  min_core_energies: 4
  momentum_cycle_or: true
  burns_mode: true
  confirm_before_place: true
  time_in_force: "gtc"
  order_type: "market"
  max_signals_per_run: 0

  energy_weights:               # optional weighting (informational)
    trend: 1.0
    momentum: 1.0
    cycle: 1.0
    sr: 1.0
    scale: 1.0

  patterns:                     # post-energy pattern triggers
    enabled: false              # disabled temporarily to expand flow for diagnostics
    modes:
      - engulf
      - inside_break
      - nr4_break

  filters:                      # additional trade-level gating
    min_atr_pct: 0.011          # relaxed to admit slightly lower volatility names
    max_extension_pct: 0.06     # reject stretched entries
    min_avg_vol50: 300000       # liquidity floor (50d avg volume)
    pullback_tolerance_pct: 0.035  # loosened to capture more pullbacks
    value_zone_max_ext_pct: 0.025   # Burns: acceptable extension from EMA20 for valid pullback entry
    value_zone_reject_tail_min: 0.40 # relaxed from 0.55 (long)
    value_zone_reject_tail_min_short: 0.40 # relaxed from 0.55 (short)
    value_zone_touch_atr_max: 0.60    # max ATR multiple below EMA20 (or above for shorts) allowed for pullback low/high
    cycle_oversold: 25               # SlowK threshold oversold (long)
    cycle_overbought: 75             # SlowK threshold overbought (short)
    cycle_cross_lookback: 3          # bars within which a valid stochastic cross must have occurred
    momentum_hist_expand_lookback: 2 # MACD histogram expansion bars required
    momentum_macd_min: 0.00          # floor for MACD magnitude (Burns often flexible)
  # removed legacy fractal thresholds (Scale covers MTF alignment)

  targets:                      # scaling / runner configuration
    enabled: false              # phase1 disable scaling; evaluate raw expectancy
    primary_R: 2.2              # placeholder (unused while disabled)
    runner_R: 0.0
    scale_out_pct: 0.0
    adx_min_for_runner: 0

  volume_tiebreak_core4: false  # relaxed: allow core-min without volume confirm (diagnostic)

  mtf:                          # higher timeframe confirmation
    enabled: true
    timeframe: "W"
    trend_filter: "macd"       # Burns: use momentum on higher timeframe
    ema_fast: 20
    ema_slow: 50
    macd_fast: 12
    macd_slow: 26
    macd_signal: 9
    counts_as_energy: false     # in Burns, Scale is core inside evaluator; no extra bonus
    reject_on_mismatch: true    # veto mismatches

### ---------- For backtesting ---------- ###
backtest:
  start_days_ago: 600
  initial_equity: 50000
  commission_per_share: 0.00
  slippage_bps: 2.0
  allow_short: false             # optional: start long-only; re-enable later
  max_open_positions: 6
  max_total_risk_pct: 0.08
  max_new_trades_per_week: 3
  touch_priority: "stop_first"
  bp_multiple: 1.0
  halt_on_equity_at_or_below: 0
  force_close_on_end: true
  time_stop:
    enabled: false   # phase1 off to allow winners time
    bars: 0
    min_R: 0.0
  early_stop:                # new soft-stop pruning
    enabled: false
    bars: 0
    min_mfe_R: 0.0
    adverse_atr_mult: 0.0
  gap_fail_safe:             # mitigate large overnight gaps
    enabled: true
    gap_R_multiple: 1.8      # tightened to reduce catastrophic losses
  loss_guard:                # early MAE hard cap
    enabled: true
    mae_R_threshold: 1.2
    bars: 5

  # Breakeven controls (engine.py uses these)
  breakeven_at_R: 1.0          # re-enabled at 1R for protection
  breakeven_intrabar: "favor_be"   # or "favor_stop"

  # Backtest entry model (independent of live order_type)
  entry_model:
    type: "limit_retrace"        # switch to pullback limit model
    retrace_to: "EMA20"
    atr_fraction: 0.15
    horizon_days: 3
