dry_run: false   # set true to preview/log only (no orders)

risk:
  account_equity: 50000        # used only if use_broker_equity: false
  use_broker_equity: true      # pull live equity from Alpaca paper acct
  risk_per_trade_pct: 0.02     # 2% risk per trade
  atr_multiple_stop: 1.5       # stop = 1.5 * ATR(14)
  reward_multiple: 2.0         # target = entry + 2R
  max_total_risk_pct: 0.10     # cap total risk across open stops
  bp_utilization: 0.95         # spend at most 95% of available buying power
  min_shares: 1

signals:
  sr_pivots:
    lookback: 60
    left: 3
    right: 3
    near_pct: 0.025            # was 0.015
    near_atr_mult: 0.75        # was 0.5
    ema50_fallback_pct: 0.025  # re-enabled fallback
    # yesterday_touch_ok defaults to true in code; add here if you want to control it
    # yesterday_touch_ok: true

# --- momentum quality controls ---
momentum:
  rsi_filter: true
  rsi_threshold: 50
  use_macd_expansion: false    # off by default; if you re-enable set expansion_min_steps: 1
  expansion_lookback: 3
  expansion_min_steps: 1
  zero_line_mode: "confirm"
  zero_cross_lookback: 3

# --- volume confirmation (any-of) ---
volume:
  rvol_window: 20
  rvol_threshold: 1.20
  ad_trend_lookback: 3
  obv_mode: "tick"             # or "slope"
  min_components: 1            # pass if >=1 of {RVOL, AD, OBV} agrees

regime:
  enabled: true
  adx_min: 16
  atr_pct_min: 0.010
  use_chop: true
  chop_window: 14
  chop_max: 60

logging:
  explain_rejects: true

fundamentals:
  enabled: false
  min_price: 5
  max_price: 1000
  min_avg_vol: 1000000
  earnings_blackout_days: 3
  sectors_allow: []
  sectors_deny: []
  profitability:
    enabled: false
    require_positive_eps_ttm: true
    min_revenue_yoy_growth_pct: 0
  news:
    enabled: true
    lookback_days: 3
    min_sentiment: -0.10
    forbid_red_flags:
      - bankruptcy
      - fraud
      - "going concern"

trading:
  # MTF can count as a 6th "bonus" energy; keep min_score=4
  min_score: 4
  confirm_before_place: true
  time_in_force: "gtc"
  order_type: "market"
  max_signals_per_run: 0

  # ---- Higher timeframe (MTF) confirmation ----
  mtf:
    enabled: true
    timeframe: "W"
    trend_filter: "ema"        # or "macd"
    ema_fast: 20
    ema_slow: 50
    macd_fast: 12
    macd_slow: 26
    macd_signal: 9
    counts_as_energy: true     # bonus point if aligned
    reject_on_mismatch: false  # never a hard veto unless set true

### ---------- For backtesting ---------- ###
backtest:
  start_days_ago: 600
  initial_equity: 50000
  commission_per_share: 0.00
  slippage_bps: 2.0
  allow_short: true
  max_open_positions: 6
  max_total_risk_pct: 0.08
  max_new_trades_per_week: 3
  touch_priority: "stop_first"
  # The next three are ignored unless engine.py implements them:
  bp_multiple: 1.0
  halt_on_equity_at_or_below: 0
  force_close_on_end: true

  # Breakeven controls (engine.py uses these)
  breakeven_at_R: 1.0
  breakeven_intrabar: "favor_be"   # or "favor_stop"

  # Backtest entry model (independent of live order_type)
  entry_model:
    type: "market"          # "market" or "limit_retrace"
    retrace_to: "EMA20"
    atr_fraction: 0.25
    horizon_days: 3
