dry_run: false   # set true to preview/log only (no orders)

risk:
  account_equity: 50000        # used only if use_broker_equity: false
  use_broker_equity: true      # pull live equity from Alpaca paper acct
  risk_per_trade_pct: 0.02     # 2% risk per trade
  atr_multiple_stop: 1.5       # stop = 1.5 * ATR(14)
  reward_multiple: 2.0         # target = entry + 2R
  max_total_risk_pct: 0.10     # (live guard; backtester has its own cap below)
  bp_utilization: 0.95         # spend at most 95% of available buying power
  min_shares: 1

signals:
  sr_pivots:
    lookback: 60          # bars to search for recent pivots
    left: 3               # pivot definition: bars to the left
    right: 3              # pivot definition: bars to the right
    near_pct: 0.015       # stricter proximity (was 0.02)
    near_atr_mult: 0.5    # or within 0.5 * ATR(14)
    ema50_fallback_pct: null  # disable EMA50 fallback for now

# --- momentum quality controls ---
momentum:
  rsi_filter: true          # keep RSI check (>=50 long, <=50 short)
  rsi_threshold: 50
  use_macd_expansion: true  # require MACD histogram expansion
  expansion_lookback: 3     # look at last N bars of MACDh
  expansion_min_steps: 2    # 

  # zero-line context for MACD line (not histogram):
  #  - none     : ignore zero-line
  #  - confirm  : require MACD>0 for longs ( <0 for shorts )
  #  - cross    : require a zero-cross within the last K bars
  zero_line_mode: "confirm"   # stricter (was "confirm")
  zero_cross_lookback: 3

volume:
  rvol_window: 20        # days for median volume
  rvol_threshold: 1.20   # stricter (was 1.20)
  ad_trend_lookback: 3   # AD slope lookback in bars
  obv_confirm: true      # also require OBV moving in the same direction

regime:
  enabled: true
  adx_min: 18           # require ADX(14) >= this (trend strength floor)
  atr_pct_min: 0.015    # require ATR14/Close >= this (volatility floor; 1.5%)
  use_chop: true        # use Choppiness Index filter
  chop_window: 14       # CHOP lookback
  chop_max: 55          # skip if CHOP > this (too rangey)

logging:
  explain_rejects: true  # keep detailed reasons visible

fundamentals:
  enabled: false

  # 1) Price range filter
  min_price: 5
  max_price: 1000

  # 2) Liquidity (use 50-day average volume)
  min_avg_vol: 1000000     

  # 3) Earnings blackout (skip if earnings within +/- N calendar days)
  earnings_blackout_days: 3

  # 4) Sector allow/deny lists (requires a fundamentals provider; otherwise ignored)
  sectors_allow: []        # e.g., ["Technology","Healthcare"]
  sectors_deny:  []        # e.g., ["Energy"]

  # 5) Tradability is handled earlier by Alpaca (filter_active_tradable)

  # Optional: basic profitability (requires provider; ignored if data missing)
  profitability:
    enabled: false
    require_positive_eps_ttm: true
    min_revenue_yoy_growth_pct: 0

  # Optional: short-term news sentiment / red-flag headlines (requires provider)
  news:
    enabled: true
    lookback_days: 3
    min_sentiment: -0.10        # require >= this; -1..1 scale
    forbid_red_flags:
      - bankruptcy
      - fraud
      - "going concern"

trading:
  min_score: 4                 # 4 out of 5 alignment
  confirm_before_place: true   # prompt before sending orders
  time_in_force: "gtc"         # "day" or "gtc"
  order_type: "market"         # "market" or "limit"
  max_signals_per_run: 0       # 0=unlimited; otherwise cap per run

  # ---- Higher timeframe (MTF) confirmation ----
  mtf:
    enabled: true
    timeframe: "W"             # resample daily → weekly
    trend_filter: "ema"        # "ema" or "macd"
    ema_fast: 20
    ema_slow: 50
    macd_fast: 12
    macd_slow: 26
    macd_signal: 9
    require_alignment: true
    reject_on_mismatch: true

### ---------- For backtesting ---------- ###
backtest:
  start_days_ago: 600
  initial_equity: 50000
  commission_per_share: 0.00
  slippage_bps: 2.0              # 0.02% on entries & exits
  allow_short: true
  max_open_positions: 6          # portfolio cap (engine uses this key)
  max_total_risk_pct: 0.08       # cap total risk across all open trades
  max_new_trades_per_week: 3
  touch_priority: "stop_first"   # if both hit same day: stop_first|target_first

  # Backtest entry model (independent of live order_type)
  entry_model:
    type: "limit_retrace"        # "market" or "limit_retrace"dry_run: false   # set true to preview/log only (no orders)

risk:
  account_equity: 50000        # used only if use_broker_equity: false
  use_broker_equity: true      # pull live equity from Alpaca paper acct
  risk_per_trade_pct: 0.02     # 2% risk per trade
  atr_multiple_stop: 1.5       # stop = 1.5 * ATR(14)
  reward_multiple: 2.0         # target = entry + 2R
  max_total_risk_pct: 0.10     # (live guard; backtester has its own cap below)
  bp_utilization: 0.95         # spend at most 95% of available buying power
  min_shares: 1

signals:
  sr_pivots:
    lookback: 60
    left: 3
    right: 3
    near_pct: 0.015            # stricter proximity (was 0.02)
    near_atr_mult: 0.5         # or within 0.5 * ATR(14)
    ema50_fallback_pct: null   # disable EMA50 fallback for now

# --- momentum quality controls ---
momentum:
  rsi_filter: true             # keep RSI check (>=50 long, <=50 short)
  rsi_threshold: 50
  use_macd_expansion: true     # require MACD histogram expansion
  expansion_lookback: 3
  expansion_min_steps: 3       # stricter (was 2)

  # zero-line context for MACD line (not histogram):
  #  - none     : ignore zero-line
  #  - confirm  : require MACD>0 for longs ( <0 for shorts )
  #  - cross    : require a zero-cross within the last K bars
  zero_line_mode: "cross"      # stricter: require recent cross
  zero_cross_lookback: 5       # lookback for the zero-cross condition

volume:
  rvol_window: 20
  rvol_threshold: 1.30         # stricter (was 1.20)
  ad_trend_lookback: 3
  obv_confirm: true            # require OBV to agree

regime:
  enabled: true
  adx_min: 18                  # trend strength floor
  atr_pct_min: 0.015           # volatility floor; 1.5%
  use_chop: true
  chop_window: 14
  chop_max: 55                 # skip if too rangey

logging:
  explain_rejects: true        # keep detailed reasons visible

fundamentals:
  enabled: false
  min_price: 5
  max_price: 1000
  min_avg_vol: 1000000
  earnings_blackout_days: 3
  sectors_allow: []
  sectors_deny: []
  profitability:
    enabled: false
    require_positive_eps_ttm: true
    min_revenue_yoy_growth_pct: 0
  news:
    enabled: true
    lookback_days: 3
    min_sentiment: -0.10
    forbid_red_flags:
      - bankruptcy
      - fraud
      - "going concern"

trading:
  min_score: 4                 # need 5/5 energies aligned
  confirm_before_place: true
  time_in_force: "gtc"
  order_type: "market"         # live setting; backtest has its own entry model
  max_signals_per_run: 0

  # ---- Higher timeframe (MTF) confirmation ----
  mtf:
    enabled: true
    timeframe: "W"             # resample daily → weekly
    trend_filter: "ema"        # "ema" or "macd"
    ema_fast: 20
    ema_slow: 50
    macd_fast: 12
    macd_slow: 26
    macd_signal: 9
    require_alignment: true
    reject_on_mismatch: true

### ---------- For backtesting ---------- ###
backtest:
  start_days_ago: 600
  initial_equity: 50000
  commission_per_share: 0.00
  slippage_bps: 2.0              # 0.02% on entries & exits
  allow_short: true
  max_open_positions: 6          # portfolio cap (engine uses this key)
  max_total_risk_pct: 0.08       # cap total risk across all open trades
  max_new_trades_per_week: 3
  touch_priority: "stop_first"   # if both hit same day: stop_first|target_first

  # Breakeven controls (used by engine.py)
  breakeven_at_R: 1.0            # move stop to entry after +1R; 0.0 disables
  breakeven_intrabar: favor_be    # or "favor_stop" for conservative ordering

  # Backtest entry model (independent of live order_type)
  entry_model:
    type: "limit_retrace"        # "market" or "limit_retrace"
    retrace_to: "EMA20"
    atr_fraction: 0.25           # ±0.25 * ATR from EMA20 in trade direction
    horizon_days: 3              # give it up to 3 bars to fill

    retrace_to: "EMA20"          # base reference
    atr_fraction: 0.25           # ±0.25 * ATR from EMA20 in trade direction
    horizon_days: 3              # give it up to 3 bars to fill
